#
# Makefile for hogfile
#

# What programs to make
PROGS = hogfile

# What source files and libs for the programs
hogfile_SRCS = hogfile.c 

#rules and targets common to all Miner makefiles
include $(MINER)/init/makefile.def
