#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

CLEAN_TARGS = *.obj

PROGS = hogfile

HOGFILE_SRCS = hogfile.c 

#rules and targets common to all Miner makefiles
include $(MINER)/init/makefile.def
