#
# Makefile for xcolor
#

# What programs to make
PROGS = xcolor

# What source files and libs for the programs
xcolor_SRCS = xcolor.c 
xcolor_LIBS = gr.lib misc.lib mem.lib iff.lib ui.lib io.lib cflib.lib cfile.lib vga.lib
xcolor_LFLAGS = option stack=150k

#rules and targets common to all Miner makefiles
include $(MINER)/init/makefile.def
