#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

CLEAN_TARGS = *.obj

INSTALL_TARGS = cfile.lib cfile.h nocfile.h

LIBS = cfile

cfile_SRCS = cfile.c

#rules and targets common to all Miner makefiles
include $(MINER)/init/makefile.def
